#############################################################################
# Makefile for building: RLibTest.app/Contents/MacOS/RLibTest
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  RLibTest.pro
# Template: app
# Command: /Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile RLibTest.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/Volumes/Transcend/work/q_project/RLibTest"'
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -IRLib/include -IRLib/include -IRLib/include -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -Iobj -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -Iobj/ui_header -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -F/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib
QMAKE         = /Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RLibTest1.0.0
DISTDIR = /Volumes/Transcend/work/q_project/RLibTest/obj/RLibTest1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib -L/Volumes/Transcend/work/q_project/RLibTest/RLib/ -lRLibQt5Osx -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework QtSql -framework QtTest -framework Security -framework ApplicationServices -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		widget.cpp obj/moc_widget.cpp
OBJECTS       = obj/main.o \
		obj/widget.o \
		obj/moc_widget.o
DIST          = /Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testlib_defines.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		RLibTest.pro widget.h main.cpp \
		widget.cpp
QMAKE_TARGET  = RLibTest
DESTDIR       = 
TARGET        = RLibTest.app/Contents/MacOS/RLibTest


first: all
####### Build rules

$(TARGET): /Volumes/Transcend/work/q_project/RLibTest/RLib/libRLibQt5Osx.a obj/ui_header/ui_widget.h $(OBJECTS)  
	@test -d RLibTest.app/Contents/MacOS/ || mkdir -p RLibTest.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RLibTest.pro /Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf /Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testlib_defines.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		RLibTest.pro \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/QtSql.prl \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtTest.framework/QtTest.prl \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile RLibTest.pro
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testlib_defines.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf:
RLibTest.pro:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/QtSql.prl:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtTest.framework/QtTest.prl:
/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile RLibTest.pro

qmake_all: FORCE

RLibTest.app/Contents/PkgInfo: 
	@test -d RLibTest.app/Contents || mkdir -p RLibTest.app/Contents
	@$(DEL_FILE) RLibTest.app/Contents/PkgInfo
	@echo "APPL????" > RLibTest.app/Contents/PkgInfo
RLibTest.app/Contents/Resources/empty.lproj: 
	@test -d RLibTest.app/Contents/Resources || mkdir -p RLibTest.app/Contents/Resources
	@touch RLibTest.app/Contents/Resources/empty.lproj
	
RLibTest.app/Contents/Info.plist: 
	@test -d RLibTest.app/Contents || mkdir -p RLibTest.app/Contents
	@$(DEL_FILE) RLibTest.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,RogerProject.RLibTest,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,RLibTest,g" -e "s,@LIBRARY@,RLibTest,g" -e "s,@TYPEINFO@,????,g" /Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >RLibTest.app/Contents/Info.plist

all: Makefile \
		RLibTest.app/Contents/PkgInfo \
		RLibTest.app/Contents/Resources/empty.lproj \
		RLibTest.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r RLibTest.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: obj/moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_widget.cpp
obj/moc_widget.cpp: /Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		RLib/include/Library.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariantList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		RLib/include/Network.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		RLib/include/DataBase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		RLib/include/Ipc.h \
		RLib/include/Utility.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QEventLoop \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTranslator \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		RLib/include/Ui.h \
		RLib/include/ui/LayerScrollView.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		RLib/include/ui/LayerWheel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		RLib/include/ui/LayerKeyborad.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QShowEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QHideEvent \
		RLib/include/ui/ItemLineEdit.h \
		RLib/include/ui/ItemSelectNumber.h \
		RLib/include/ui/LayerBlock.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMovie \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		widget.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/moc
	/Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Volumes/Transcend/work/q_project/RLibTest -I/Volumes/Transcend/work/q_project/RLibTest/RLib/include -I/Volumes/Transcend/work/q_project/RLibTest/RLib/include -I/Volumes/Transcend/work/q_project/RLibTest/RLib/include -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtTest.framework/Headers -I/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Qt5.7.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Qt5.7.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Qt5.7.0/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Qt5.7.0/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Qt5.7.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Qt5.7.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib widget.h -o obj/moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_header/ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_header/ui_widget.h
obj/ui_header/ui_widget.h: widget.ui \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/uic
	/Users/chenchaowei/Qt5.7.0/5.7/clang_64/bin/uic widget.ui -o obj/ui_header/ui_widget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: main.cpp widget.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		RLib/include/Library.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariantList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		RLib/include/Network.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		RLib/include/DataBase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		RLib/include/Ipc.h \
		RLib/include/Utility.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QEventLoop \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTranslator \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		RLib/include/Ui.h \
		RLib/include/ui/LayerScrollView.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		RLib/include/ui/LayerWheel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		RLib/include/ui/LayerKeyborad.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QShowEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QHideEvent \
		RLib/include/ui/ItemLineEdit.h \
		RLib/include/ui/ItemSelectNumber.h \
		RLib/include/ui/LayerBlock.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMovie \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/widget.o: widget.cpp widget.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		RLib/include/Library.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariantList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		RLib/include/Network.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		RLib/include/DataBase.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QVariant \
		RLib/include/Ipc.h \
		RLib/include/Utility.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QEventLoop \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTranslator \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		RLib/include/Ui.h \
		RLib/include/ui/LayerScrollView.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		RLib/include/ui/LayerWheel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		RLib/include/ui/LayerKeyborad.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QShowEvent \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QHideEvent \
		RLib/include/ui/ItemLineEdit.h \
		RLib/include/ui/ItemSelectNumber.h \
		RLib/include/ui/LayerBlock.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QMovie \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		obj/ui_header/ui_widget.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QByteArray \
		/Users/chenchaowei/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qbytearray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/widget.o widget.cpp

obj/moc_widget.o: obj/moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_widget.o obj/moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

